# build the dockerfiles from the microservices
# and run the containers

services:
  stock:
    build:
      context: ../Microservices/Stock
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    environment:
      - API_KEY=${STOCK_API_KEY}
  prefs:
    build:
      context: ../Microservices/Prefs
      dockerfile: Dockerfile
    ports:
      - 8084:8080
    environment:
      - SPRING_PROFILES_ACTIVE=local

  mongodb:
    image: mongo:7.0.5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: pda
    volumes:
      - ./data:/data/db