# build the dockerfiles from the microservices
# and run the containers

services:
  bff:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - OUR_API_KEY=${OUR_API_KEY}
      - SPRING_PROFILES_ACTIVE=docker
  
  stock:
    build:
      context: ../Microservices/Stock
      dockerfile: Dockerfile
    ports:
      - 8083:8080
    environment:
      - API_KEY=${STOCK_API_KEY}
      - OUR_API_KEY=${OUR_API_KEY}
  prefs:
    build:
      context: ../Microservices/Prefs
      dockerfile: Dockerfile
    ports:
      - 8084:8080
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - OUR_API_KEY=${OUR_API_KEY}
    depends_on:
      - mongodb

  chatgpt:
    build:
      context: ../Microservices/Chatgpt
      dockerfile: Dockerfile
    ports:
      - 8085:8080
    environment:
      - API_KEY=${OPENAI_API_KEY}
      - OUR_API_KEY=${OUR_API_KEY}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}

  maps:
    build:
      context: ../Microservices/Maps
      dockerfile: Dockerfile
    ports:
      - 8086:8080
    environment:
      - API_KEY=${MAPS_API_KEY}
      - OUR_API_KEY=${OUR_API_KEY}

  speisekarte:
    build:
        context: ../Microservices/Speisekarte
        dockerfile: Dockerfile
    ports:
        - 8087:8080

  wetter:
    build:
        context: ../Microservices/Wetter
        dockerfile: Dockerfile
    ports:
        - 8088:8080
    environment:
        - API_KEY=${WEATHER_API_KEY}
        - OUR_API_KEY=${OUR_API_KEY}

  news:
    build:
        context: ../Microservices/News
        dockerfile: Dockerfile
    ports:
        - 8082:8080
    environment:
        - API_KEY=${NEWS_API_KEY}
        - OUR_API_KEY=${OUR_API_KEY}

  contacts:
    build:
      context: ../Microservices/Contacts
      dockerfile: Dockerfile
    ports:
      - 8089:8080
    environment:
      - API_KEY=${CONTACTS_API_KEY}
      - OUR_API_KEY=${OUR_API_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

  mongodb:
    image: mongo:7.0.5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: pda
    volumes:
      - ./data:/data/db